### ISSUE TITLE
Terminal Questions Various Colors Support

### ISSUE THREAD

**Issue by aircha** [avaj-java/installer-maker#21]
I hope you will be able to support the color of the wording of the questions in the terminal.

Like this
![image](https://user-images.githubusercontent.com/4676179/31811118-555ed8a2-b5b9-11e7-868e-d4be64d40ded.png)

This will improve readability greatly.

**Comment by souljungkim** [comment]
@aircha 
I found it. Maybe we can implement it.
https://stackoverflow.com/questions/5762491/how-to-print-color-in-console-using-system-out-println

**Comment by souljungkim** [comment]
https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by souljungkim** [comment]
or https://logback.qos.ch/manual/layouts.html#coloring

**Comment by souljungkim** [comment]
# you can set color

### 1. Color List
green, yellow, blue, magenta, cyan, white, gray, boldRed, boldGreen, boldYellow, boldBlue, boldMagenta, boldCyan, boldWhite

### 2. Property
description | property | default
---|---|---
`color ` | Global default color |
`descColor` | Global desc color | yellow
`questionColor` | Global question color | yellow
`{JOBNAME}.{TASKNAME}.color` | Every task default color | 
`{JOBNAME}.{TASKNAME}.descColor` | Every task desc color | 
`{JOBNAME}.{TASKNAME}.questionColor` | Every task question color | 

### 3. Partially applying colors
1. Jansi grammar
    - https://github.com/fusesource/jansi#example-usage

2. you can use jansi grammer on some property
    - `{JOBNAME}.{TASKNAME}.desc`  
    - `{JOBNAME}.{TASKNAME}.question`

3. example

- task
```yml
builder:
  testTask:
    desc: 'It is tree'
    color: green
    task: notice
    msg: 'Hello World. It is tree. you know?'
```

- desc
```yml
builder:
  testTask:
    desc: 'It is tree'
    descColor: green
    task: notice
    msg: 'Hello World. It is tree. you know?'
```

- desc (partially applying)
```yml
builder:
  testTask:
    desc: '@|cyan It|@ is @|green tree|@'
    task: notice
    msg: 'Hello World. It is tree. you know?'
```

- question
```yml
builder:
  testQuestionTask:
    question: 'It is tree. do you like it?'
    questionColor: cyan
    task: QuestionYN
    answer:
      default: Y
```

- question (partially applying)
```yml
builder:
  testQuestionTask:
    question: '@|cyan It|@ is @|green tree|@. do you like it?'
    task: QuestionYN
    answer:
      default: Y
```
