### ISSUE TITLE
More flexible command system (Custom Command)

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#26]
# 1. Custom Command
## BEFORE
Only specific commands are allowed
`init`, `clean`, `build`, `help`, `test`, `macgyver`

## AFTER
You can create `additional commands` like other build tools(Gradle, Gulp, Grunt...).
(but, Too many features will not be noticed, since users can be confused.) ❓ 

1. Write a script
    - build.yml
    ```yml
    build:
      step1:
        task: notice
        msg: Let's start build Install
      .
      .

    macdonald:
      greeting:
        task: notice
        msg: good morning
  
      promotion:
        task: notice
        msg: i lovin it!
      ```

2. Command on terminal
    ```bash
    installer-maker macdonald
    ```

3. Result
    ```log
    good morning
    i lovin it!
    ```

# 2. Refactoring 
## BEFORE
3 properties files

- builder.yml
  ```yml
  builder:
    step1:
      task: notice
      msg: hi hello good morning
  .
  .
    ```

- receptionist.yml
  ```yml
  receptionist:
    step1:
      task: question
      question: hi what do you like?
  .
  .
  ```

- installer.yml
  ```yml
  installer:
    step1:
      task: copy
      desc: copy help file
      from: ${installer.home}/data/help/*
      to: ~/help
  .
  .
  ```

### AFTER
2 properties files - Change more intuitively (The first part of the attribute is the command on script files.)

- installer-maker.yml
  ```yml
   build:
    step1:
      task: notice
      msg: Let's start build Install
    .
    .      
  ```
  
- installer.yml
  ```yml
  ask:
    step1:
      task: question
      question: hi what do you like?
  .
  .
  ```

  ```yml
  install:
    step1:
      task: copy
      desc: copy help file
      from: ${installer.home}/data/help/*
      to: ~/help
  .
  .
  ```
