### ISSUE TITLE
Importing some properties from a property file(properties, yml)

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#32]
# SET 
- Add target option
```
commandName:
  taskName:
    task: set
    properties.file: ./some.properties
    target: property.name.to.import
```
- Imagine more
```
target: can.use.*.wild.card.
```
```
target: '["several.property.one", "several.property.two"]'
```
```
target: 
  - several.property.one
  - several.property.two
```
