### ISSUE TITLE
[Special Task] 'goto' to jump to specific task

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#41]
# TASK
## GOTO

- example) goto.task
```
command1:
  step1:
    task: goto
    goto.task: step3

  step2:
    task: notice
    msg: step2

  step3:
    task: notice
    msg: step3
```

- result
```
step3
```

- example) goto.command
```
command1:
  step1:
    task: goto
    goto.command: command2

  step2:
    task: notice
    msg: step2

  step3:
    task: notice
    msg: step3

command2:
  step1:
    task: notice
    msg: step1 on command2

  step2:
    task: notice
    msg: step2 on command2
```

- result
```
step1 on command2
step2 on command2
```
