### ISSUE TITLE
else (condition)

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#42]
```
newcom: 
  q1:
    task: question
    question: New container name?
    property: var.container.name

  q2:
    task: question
    question: RDP port?
    property: var.port.rdp

  q3:
    task: question
    question: SSH port?
    property: var.port.ssh

  run1:
    ifport: '{"${var.port.rdp}": false, "${var.port.rdp}": false}'
    task: exec    
    mode.ignore.error: true
    command:
      - docker run --privileged --name shared-docker -d docker:stable-dind --storage-driver=overlay2
      - docker run -d --link shared-docker:docker --shm-size 1g --name uxrdp-dind-${var.container.name} --hostname docker-terminal -p ${var.port.rdp}:3389 -p ${var.port.ssh}:22 danielguerra/ubuntu-xrdp-docker
    else:
      task: notice
      msg: Check Port Status
```
