### ISSUE TITLE
Command task to run another command

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#44]

**Comment by souljungkim** [comment]
# Task: Command

## 1. single command
```yaml
command:
  step1:
    task: command
    command: command2 

command2:
  step1:
    task: notice
    msg: hello2
```

## 2. multiple command
```yaml
command:
  step1:
    task: command
    command: command2 command3

command2:
  step1:
    task: notice
    msg: hello2

command3:
  step1:
    task: notice
    msg: hello3
```

## 3. multiple command
```yaml
command:
  step1:
    task: command
    command: 
      - command2 
      - command3
      - command4

command2:
  step1:
    task: notice
    msg: hello2

command3:
  step1:
    task: notice
    msg: hello3

command4:
  step1:
    task: notice
    msg: hello4
```

**Comment by souljungkim** [comment]
# Task: Restart

```yaml
command:
  step1:
    task: notice
    msg: Hello?

  step2:
    task: question
    question: where do you want to see?

  step3:
    task: exec
    command: ls ${command.step2.answer}

  step4:
    task: restart
```
