### ISSUE TITLE
More Task (Sleep, Exit, Restart, Back)

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#51]

**Comment by souljungkim** [comment]
# New Tasks

## Sleep
```yaml
command_name:
  task1:
    task: notice
    msg: hi

  task2:
    task: sleep
    second: 2

  task3:
    task: notice
    msg: My name is Hotdog.
```
- result
```
hi
My name is Hotdog
hi
My name is Hotdog
.
.
```

## Exit
```yaml
command_name:
  task1:
    task: notice
    msg: hi

  task2:
    task: exit

  task3:
    task: notice
    msg: My name is Hotdog.
```
- result
```
hi
```

## Restart
```yaml
command1:
  task1:
    task: question
    desc: Who are you?

  task2:
    task: command
    command: command2

command2:
  task1:
    task: notice
    msg: hello ${command1.task1.answer}?

  task2:
    task: restart
```
- result
```
Who are you?
> someone
hello someone?
Who are you?
> somone
hello someone?
.
.
```

## Back
```yaml
command1:
  task1:
    task: question
    desc: Who are you?

  task2:
    task: notice
    msg: Hello ${command1.task1.answer}? My name is Hotdog.

  task3:
    task: command
    command: command2

command2:
  task1:
    task: question
    desc: How are you?

  task2:
    task: back
    to: command1.task2
```
- result
```
Who are you?
> someone
Hello someone? My name is Hotdog.
How are you?
> good
Hello someone? My name is Hotdog.
How are you?
> good!!
.
.
```
