### ISSUE TITLE
More conditional features. (iffile, ifproperty)

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#56]
## ifproperty
```yaml
some.property: I love you

command_check_property:
  task1:
    ifproperty: '{"some.property": true}'
    task: notice
    msg: ${some.property}
```
## iffile
```yaml
command_check_file:
  task1:
    iffile: '{"/home/ubuntu/test.txt": true, "/home/ubuntu/test2.txt": false}'
    task: notice
    msg: test.txt (O)   test2.txt (X)
```
