### ISSUE TITLE
[QuestionChoice Task] Selection Order

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#60]
## Before
```yaml
testman:

  main:
    task: questionChoice
    desc: Choose what to do
    answer:
      default: 2
      options: '{
        "1":"Test Install",
        "2":"Test Install with Docker",
        "3":"Test Application[ gradle test ]",
        "4":"Build War       [ gradle clean war -Plicense=true ]",
        "5":"Build War       [ gradle clean war ]",
        "6":"Build Installer [ installer-maker clean build --build --license ]",
        "7":"Build Installer [ installer-maker clean build --build ]",
        "8":"Build Installer [ installer-maker clean build ]"
      }'
      values: '{
        "1":"installman",
        "2":"dockerman",
        "3":"testmeta",
        "4":"buildwar1",
        "5":"buildwar2",
        "6":"buildinstaller1",
        "7":"buildinstaller2",
        "8":"buildinstaller3"
      }'
    property: temp.command
```

## After
```yaml
testman:

  main:
    task: questionChoice
    desc: Choose what to do
    answer:
      default: 2
      options: 
        - 1) Test Install
        - 2) Test Install with Docker
        - 3) Test Application[ gradle test ]
        - 4) Build War       [ gradle clean war -Plicense=true ]
        - 5) Build War       [ gradle clean war ]
        - 6) Build Installer [ installer-maker clean build --build --license ]
        - 7) Build Installer [ installer-maker clean build --build ]
        - 8) Build Installer [ installer-maker clean build ]      
      values:
        - 1) installman
        - 2) dockerman
        - 3) testmeta
        - 4) buildwar1
        - 5) buildwar2
        - 6) buildinstaller1
        - 7) buildinstaller2
        - 8) buildinstaller3
    property: temp.command
```
