### ISSUE TITLE
[Variable] default function when mode.variable.question

### ISSUE THREAD

**Issue by souljungkim** [avaj-java/installer-maker#61]
### This option is useful when you need to ask questions about variables.(It generate question automatically before task)
```yaml
mode.variable.question.before.task: true
```
```yaml
mode.variable.question.before.command: true
```

### You can use like this 
```
test-command:
  task1:
    task: exec
    mode.variable.question.before.task: true
    command: echo Hello ${var1}? this is ${var2}.
```
```bash
hoya test-command
```

### and then, Result is
```bash
var1[]?
> hoya

var2[]?
> program

Hello hoya? this is program.
```

### Add nvl function and default value
```
test-command:
  task1:
    task: exec
    mode.variable.question.before.task: true
    command: echo Hello ${var1().nvl(hoya)}? this is ${var2().nvl(program)}.
```

### and then, Result is
```bash
var1[hoya]?
> hoya

var2[program]?
> program

Hello hoya? this is program.
```
